#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     forwardsTilt,   sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S2_C1_1,     left,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     right,         tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    rearFlipper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    frontFlipper,         tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h"
#include "JoystickDriver.c"
#include "PID.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void init();

task main()
{
	init();
	waitForStart();
 	while(true)
 	{
	 		getJoystickSettings(joystick);

	 		if(abs(joystick.joy1_y1)<10)
				joystick.joy1_y1 = 0;
			if(abs(joystick.joy1_y2)<10)
				joystick.joy1_y2 = 0;

	 		motor[left] = joystick.joy1_y1 * (100.0/128.0);
	 		motor[right] = joystick.joy1_y2 * (100.0/128.0);
	 		wait1Msec(5);
 	}
}

void init() {
	motor[left] = 0;
	motor[right] = 0;
	nMotorPIDSpeedCtrl[left] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[right] = mtrSpeedReg;
	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;
}
