#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\TEST\Documents\Programming\r-d\PIDSwegWay\T4Math.c"

#include "drivers/hitechnic-accelerometer.h"


task main()
{
	INTR vx,dx,vy,dy,vz,dz;
	initIntr(vx);
	initIntr(dx);
	initIntr(vy);
	initIntr(dy);
	initIntr(vz);
	initIntr(dz);

	int x,y,z,offsetx,offsety,offsetz;

	PlaySound(soundBeepBeep);
	wait1Msec(1000);
	PlaySound(soundBeepBeep);

	HTACreadAllAxes(accel,offsetx,offsety,offsetz);

	for(;;){
		HTACreadAllAxes(accel,x,y,z);
		if(abs(x-offsetx)<5)x=offsetx;
		if(abs(y-offsety)<5)y=offsety;
		if(abs(z-offsetz)<5)z=offsetz;

		nxtDisplayCenteredTextLine(1,"%d - %d",x,offsetx);
		nxtDisplayCenteredTextLine(2,"%d - %d",y,offsety);
		nxtDisplayCenteredTextLine(3,"%d - %d",z,offsetz);
		nxtDisplayCenteredTextLine(4,"%f",integrate(dx, integrate(vx, (x-offsetx)/20.0)));
		nxtDisplayCenteredTextLine(5,"%f",integrate(dy, integrate(vy, (y-offsety)/20.0)));
		nxtDisplayCenteredTextLine(6,"%f",integrate(dz, integrate(vz, (z-offsetz)/20.0)));
		wait1Msec(10);
	}
}
