#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     oneMotorToRuleThemAll, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
NewMotorsTest.c
Just checkin out if the NeveRest 40 Motors from Andy Mark's website work as expected.
PID ftw?

LastUpdateOn: 10-29-14
LastUpdatedBy: David
Status: nothing to commit, working directory clean
*/

#include "lib\Nonviolence.h"

task main()
{
	startTask(nonviolenceTask);

	const int w = 5000;
	motor[oneMotorToRuleThemAll] = 100;
	wait1Msec(1000);
	motor[oneMotorToRuleThemAll] = 0;
	//wait1Msec(1000);
	motor[oneMotorToRuleThemAll] = 2;
	wait1Msec(10000);
	displayCenteredTextLine(0, "%d", nMotorEncoder[oneMotorToRuleThemAll]);

	playSound(soundBeepBeep);
	nonviolence(oneMotorToRuleThemAll,100);
	wait1Msec(w);
	displayCenteredTextLine(1, "%d", nMotorEncoder[oneMotorToRuleThemAll]);
	playSound(soundBeepBeep);
	nonviolence(oneMotorToRuleThemAll,0);
	wait1Msec(w);
	displayCenteredTextLine(2, "%d", nMotorEncoder[oneMotorToRuleThemAll]);
	playSound(soundBeepBeep);	playSound(soundBeepBeep);

	for(;;);

	stopTask(nonviolenceTask);
}
